output_dir: ckpt
remove_unused_columns: true
per_device_train_batch_size: 16
gradient_accumulation_steps: 4
per_device_eval_batch_size: 64
learning_rate: 0.0001
lr_scheduler_type: constant
max_steps: 25000
eval_strategy: steps
eval_steps: 100
save_strategy: steps
save_steps: 100
save_total_limit: 1
load_best_model_at_end: true
save_only_model: true
logging_steps: 1


